# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='mp',
            field=models.TextField(blank=True),
        ),
    ]
