# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono1', models.CharField(max_length=100, null=True, unique=True)),
                ('telefono2', models.CharField(max_length=100, null=True, unique=True)),
                ('horario', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100, null=True, unique=True)),
                ('mapa', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.TextField(editable=False)),
            ],
        ),
    ]
