# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('icono', models.CharField(max_length=25)),
                ('link', models.CharField(max_length=100)),
                ('respuesta', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name_plural': 'Datos SINAM'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Compras (FAQ)'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='respuesta',
            field=models.TextField(),
        ),
    ]
