# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_remove_redessociales_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='redessociales',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
