# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_redessociales_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('desarrollo', models.TextField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Nosotros',
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id'], 'verbose_name_plural': 'Compras (FAQ)'},
        ),
    ]
