# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20170928_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='horario',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
